spring.application.name=hotel-booking-app
server.port = 8000
spring.profile=Production
server.error.include-stacktrace=ALWAYS
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5434/hotel-booking-app
spring.datasource.username=postgres
spring.datasource.password=123456789
spring.jpa.show-sql=true

jwt-secret="C6UlILsE6GJwNqwCTkkvJj9O653yJUoteWMLfYyrc3vaGrrTOrJFAUD1wEBnnposzcQl"
jwt-expiration-ms=86400000